Repository curveball/http-errors, pull requests merged in 2022-01, with the labels that each got.

#27 Update all dependencies and configs
  .eslintrc.json
  LICENSE
  package-lock.json
  package.json
  src/index.ts
  test/tests.ts
  tsconfig.json
Labels: enhancement, dependencies

#26 feat(*): fix typo in 403 title
  src/index.ts
Labels: bug

#28 Widen the argument for isHttpError/isHttpProblem to 'unknown'.
  src/index.ts
Labels: enhancement
